### ISSUE TITLE
Question About Compatibility

### ISSUE THREAD

**Issue by fdalto** [saharmor/realtime-transcription-playground#5]
First, forgive me for asking here in the problems section.
I found your article on Meduim, and now this repository, I didn't know how to contact you. I'm participating in the development of an APP for voice recognition in Portuguese, as a consultant. I'm not a programmer. I would like to know if it is possible to create an APP that does voice recognition and type in another APP such as Word. Our goal would be to create an ADD-on for a third-party PACS system, but I would like to try it out initially. I currently only find dictation programs for websites on the web. From what I understand, it might be possible to create a Java App that generates characters like a virtual keyboard in other APPs, would it be possible?

**Comment by saharmor** [comment]
Hey! Seems like you're looking to learn about the ability to integrate to 3rd party software such as Microsoft Word to be able to input dictated text into these apps. If that's the case, it would depend on the kind of software you'd like to integrate with. For example, you could start here if you're looking to work with Word https://developer.microsoft.com/en-us/word

Nevertheless, as this is not an issue regarding this package, I'm closing this issue now.

**Comment by fdalto** [comment]
Hello. Yes you are right, that not an issue.
I used word as an example, what I need is to type into third part Apps
(other apps).

Do you have an example of implementation of your package as this?

Sorry if I'm bothering, but I could only find your job to solve my
problem...

Thank you

Em dom., 24 de out. de 2021 20:26, Sahar ***@***.***>
escreveu:
